### ISSUE TITLE
palm position always returns 0. 0. 0.

### ISSUE THREAD

**Issue by matcham** [NiccoloGranieri/Reach#8]
Reach 1.0.1 + latest Orion drivers 

Reach always sends 
 /Right/palm 0. 0. 0.
 /Left/palm 0. 0. 0.

**Comment by NiccoloGranieri** [comment]
Hi @matcham, when you say latest Orion drivers are you talking about Orion v4? If so, Reach is not yet compatible with v4 due to all the major changes that were made since v3. If you're interested in using Reach, please consider downloading Orion v3.2.1 from [here](https://developer-archive.leapmotion.com/downloads/external/v3-developer-beta/windows?version=3.2.0.45911).

If you're encountering the issue with Orion v3, would you mind expanding on the issue in order for me to investigate it? Thanks.

**Comment by matcham** [comment]
I'm using Orion 4.0.0+52173 ...
everything seems to work fine (exepted palm position)
so for now I will stick to this version, as tracking seems to be a bit improved and I can live without palm position for now...
thanks

**Comment by NiccoloGranieri** [comment]
Ok, then the mystery is solved! I am surprised Reach is even working with Orion v4. Good to know!

**Comment by matcham** [comment]
on your wiki you say 
"Download, install and launch the latest Leap Motion Orion SDK "
..maybe add a line to say it's Orion v3.2.1 only :-)
